# another系のmigrationのために存在。できればdatabase.ymlに統合したい
default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: 'switchpoint'
  username: 'switchpoint'
  password: 'switchpoint'
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_ANOTHER") { 'switchpoint_another' } %>
  host: <%= ENV.fetch("DB_HOST_ANOTHER_MASTER") { 'localhost' } %>

test:
  <<: *default
  database: <%= ENV.fetch("TEST_DB_NAME_ANOTHER") { 'switchpoint_another_test' } %>
  host: <%= ENV.fetch("TEST_DB_HOST_ANOTHER_MASTER") { 'localhost' } %>

production:
  <<: *default
